### ISSUE TITLE
Details of installation 

### ISSUE THREAD

**Issue by omkartelee08** [icclab/cyclops#6]
Hi,

I have an OpenStack Mitaka cloud running in my systems.
Can you simply tell me in steps, how can I use Cyclops with Dashboard. I am confused about versions you support.
For Ex: 
I need to install cyclops on controller node then dashboard on some other VM, and configure the endpoints.

**Comment by ManuPerezBelmonte** [comment]
Hello, 

The example configuration is almost the easiest setup but there is one step that you will have to do during the installation to make everything work properly. 

We do really recommend you to use the easiest setup, which would be having Cyclops deployed on a separate host/VM from the controller node, so you would only have to run the following commands:
`bash install_dependencies.sh` and `bash start_cyclops.sh`. And then proceed with the Usage Collectors and Dashboard installations.

However, if you want to deploy Cyclops in the controller node, it only differs in the fact that RabbitMQ might already be installed on it, so the configuration files of the individual services will need to be changed in order to use the already existing RabbitMQ with it's credentials and endpoints.
The configuration files can be found in 
`cyclops/core/billing/config/billing.conf`
`cyclops/core/udr/config/udr.conf`
`cyclops/core/rc/cdr/config/cdr.conf`
`cyclops/core/rc/rate/config/rate.conf`
After editing them you could install separately the dependencies (under `cyclops/install` folder) omitting the `install_rabbitmq.sh` or simply commenting/removing the line on the `install_dependencies.sh` file.

Once Cyclops core is installed, the only remaining steps are how to deploy the Dashboard and the Usage Collector that is going to be used.

Dashboard installation is as easy as following the [steps shown in it's own repository](https://github.com/icclab/cyclops-dashboard). 

Finally you would have to install the usage collector that you prefer. For OpenStack we have developed the [OpenStack Event Collector](https://github.com/icclab/cyclops/tree/master/collectors/openstack-events) and the [OpenStack Ceilometer Collector](https://github.com/icclab/cyclops/tree/master/collectors/openstack-ceilometer). In both of them you can find the steps to follow in order to set them up.

Please, let us know if you have any other questions or get stuck while following the steps above.

Cheers,
Cyclops team.

**Comment by Extrodox** [comment]
I am trying to install Cyclops in the controller only.

**1)** **confusion In cyclops repo**
If I comment out `install_rabbitmq.sh`. It says Rabbitmq management plugin is missing.
I am not sure from `cyclops/install/install_rabbitmq.sh` what lines to comment out.

**2)** **confusion In conf files**
Is there is good documentation describing configuration details of following files?

```
cyclops/core/billing/config/billing.conf
cyclops/core/udr/config/udr.conf
cyclops/core/rc/cdr/config/cdr.conf
cyclops/core/rc/rate/config/rate.conf

```
In my Rabbitmq I have two users. guest and openstack. 
guest user is as usual on localhost and this user is administrator.
openstack user is used by my OpenStack setup and this user is **not** administrator.
Which user details to be written for Publisher and Consumer?
which IP address to be written here, my controller IP or localhost?

**3)** **Dashboard**
In my controller, there is already openstack dashboard running with 8080 port.
How to change the port for cyclops Dashboard.

**4)** **cyclops-dashboard/conf/dashboard.conf**
Again which IP address to be written here, my controller IP or localhost?

**5)** **collector openstack-ceilometer.conf**
What is OpenstackAccount ? Do you mean admin account here?
Again same confusion with Publisher and Consumer details.

**6)** **openstack-ceilometer collector**
how to start this exactly?

**Comment by ManuPerezBelmonte** [comment]
Hello, 

As we said in the previous response, installing Cyclops in the Controller node itself is a little bit trickier, but let's see...

Responding your first question, the `install_rabbitmq.sh` file makes several things, first of all installs the rabbitmq server itself (which you don't need if you already have in the host) and finally enables the `rabbitmq_management` plugin. This is done in order to extract the **rabbitmqadmin** cli from the host itself. **rabbitmqadmin** is used in the following step of the `install_dependencies.sh` file when `setup_bindings.sh` is executed. If you already have the rabbitmq server installed, you could probably just skip the first line so all the commands are executed but the install.

Regarding the configuration files, yes, everything is well documented in our [wiki pages](https://github.com/icclab/cyclops/wiki/Configuration). If you still have some doubts after reading the wiki, please let us know. In order to make your doubts also a little bit more clear, you can point to localhost, and you have to decide define the credentials that have access to the queues that you just created in the previous step.

About the Dashboard, the port selection was not documented, sorry I will change this asap. To do it please add the following line with whatever port you want in the `application.properties` file `server.port=8080`, you will find it in the Dashboard main folder.

Regarding the configuration, again the same everything is documented on it's own [wiki page](https://github.com/icclab/cyclops-dashboard/wiki/Configuration-Documentation-v0.2.1), the Ip must be where it's deployed, both should work, we always use localhost though.

You can start the collector by [running it's JAR itself](https://github.com/icclab/cyclops/tree/master/collectors/openstack-ceilometer#run-the-jar-file), it's a simple command that let's you choose in which port do you want to deploy it.

Please let us know if this helped you :)

Cheers!
Cyclops team.

**Comment by Extrodox** [comment]
I did what you said.But I am getting this output. What am I doing wrong?
<img width="1128" alt="screen shot 2017-02-03 at 4 26 04 pm" src="https://cloud.githubusercontent.com/assets/2028161/22588826/923cd4fc-ea2d-11e6-990a-3c8559752eb9.png">

**Comment by ManuPerezBelmonte** [comment]
Hi, 

Could you please send me a screenshot of your rabbitmq queues?

Thanks.

**Comment by Extrodox** [comment]
Here it is.
![screencapture-69-197-163-66-15672-1486120307522](https://cloud.githubusercontent.com/assets/2028161/22589318/b3b999d8-ea2f-11e6-848f-a29eb307edf6.png)

**Comment by ManuPerezBelmonte** [comment]
Ok, cyclops.udr.consume is empty, that means that Ceilometer Collector is not sending data. The collector itself has got a default frequency of 15 minutes, which could be one reason, however you should have gotten at least the initial pull. Could you show me now the exchanges?

**Comment by Extrodox** [comment]
Here is rabbitMQ exchange. 
![screencapture-69-197-163-66-15672-1486120523422](https://cloud.githubusercontent.com/assets/2028161/22589410/35e4e264-ea30-11e6-83fd-93136e4217a8.png)

**Comment by ManuPerezBelmonte** [comment]
Is the cyclops.ceilometer.collector.broadcast binded to the cyclops.udr.consume? you can see this by clicking on the name of the queue and opening the bindings tab. 

If the binding is not set up, that could be a problem.

However, if the binding is set up, then Ceilometer Collector is not sending information to UDR because the cyclops.udr.consume queue had 0 queued messages and no traffic in it. 

Could you please check that and then we try to get the solution?

**Comment by Extrodox** [comment]
Looks like it is bounded.

![screencapture-69-197-163-66-15672-1486120964332](https://cloud.githubusercontent.com/assets/2028161/22589628/3906a94a-ea31-11e6-8a5d-1c0b55d888fd.png)

I also have attached my endpoint list for OpenStack. Do let me know if there is any issue in it.

<img width="1350" alt="screen shot 2017-02-03 at 4 54 16 pm" src="https://cloud.githubusercontent.com/assets/2028161/22589672/757fcd66-ea31-11e6-80a1-304d08918063.png">

**Comment by ManuPerezBelmonte** [comment]
Well with this we can track the error to the Collector itself, could you send me it's config file?

**Comment by Extrodox** [comment]
Openstack Ceilomenter collector config
<img width="574" alt="screen shot 2017-02-03 at 4 58 06 pm" src="https://cloud.githubusercontent.com/assets/2028161/22589763/f67e73ae-ea31-11e6-81cd-0642fdb90fcb.png">

**Comment by ManuPerezBelmonte** [comment]
I can see that you have a http://controller:5000/v3 from the screenshot you sent me before, however I don't know if you do have the /v2.0 version of keystone deployed or if the endpoint is accessible. 
This might be the initial problem as Ceilometer collector needs to authenticate itself before requesting the usage data and start the whole process.

We have developed and tested the collector using Keystone 2.0 and that might be the problem, could you please send me a tail or your ceilometer collector logs? They should be in either `/var/log/cyclops/openstack_ceilometer/errors.log` or `/var/log/cyclops/openstack_ceilometer/trace.log`

**Comment by Extrodox** [comment]
This screenshot has both log files in it.
I tried to use the url with /2.0 but apparently we dont it.
What can be the work around?

<img width="1038" alt="screen shot 2017-02-03 at 5 06 01 pm" src="https://cloud.githubusercontent.com/assets/2028161/22589989/1d889050-ea33-11e6-9213-a2303ac93c1b.png">

**Comment by ManuPerezBelmonte** [comment]
It looks exactly like that is the problem, it can not authenticate against the v2.0 ip so the execution stops. Currently there is no workaround, but now that we know the problem I will start working on it and release a different branch/multi-keystone support and I might be able to release it over next week.

I will also review the code to fix some minor things that I saw from that logs and update everything that has been developed on the meantime.

Cheers.

**Comment by Extrodox** [comment]
Do let me know.

**Comment by Extrodox** [comment]
I have been able to enable /v2.0 endpoints. Now my endpoint list looks like this. 
I tried with cyclops again but still the same issue.

<img width="1059" alt="screen shot 2017-02-05 at 1 19 31 am" src="https://cloud.githubusercontent.com/assets/2028161/22621076/30d9578e-eb41-11e6-9760-7a06dce9093b.png">

**Comment by Extrodox** [comment]
I have been able to enable Cyclops v2.0 successfully but still, dashboard is not working. 
please find more details here. https://github.com/icclab/cyclops-dashboard/issues/6

**Comment by ManuPerezBelmonte** [comment]
Hello Extrodox, 

If you could enable the Keystone v2.0 endpoints, and the Collector logs say that data has been pulled, could you please send me a screenshot of the RabbitMQ queues? My guess is, if the data is being pulled, the UDR micro service is waiting for a trigger to generate the data records, but I would like to see if that's the reason.

**Comment by Extrodox** [comment]
Hi @ManuPerezBelmonte,

Please have a look.

![screencapture-69-197-163-66-15672-1486373160715](https://cloud.githubusercontent.com/assets/2028161/22641369/76efea3a-ec7c-11e6-8671-caa7566f3757.png)

**Comment by Extrodox** [comment]
Also here are screenshots of udr command and udr consume.


![screencapture-69-197-163-66-15672-1486373555601](https://cloud.githubusercontent.com/assets/2028161/22641602/6461679e-ec7d-11e6-8ffd-4dee1094d7fb.png)

----------------------------------------------------------------------------------------------------

![screencapture-69-197-163-66-15672-1486373549261](https://cloud.githubusercontent.com/assets/2028161/22641603/64622c1a-ec7d-11e6-8962-948a274a33af.png)

**Comment by ManuPerezBelmonte** [comment]
Thanks, that is exactly what I wanted to ask for. Everything seems to be set up properly. Would you like to give me your Skype ID and we could solve it over there?

**Comment by Extrodox** [comment]
I just have sent you a skype request.

**Comment by omkartelee08** [comment]
where do I need to install  OpenStack Ceilometer Collector ?

How does it communicates with my controller ? 
Can I install all 3 components on single VM, different than controller ?

**Comment by ManuPerezBelmonte** [comment]
Hello @omkartelee08 you can install the Ceilometer Collector (or the collector that you want) in any host/vm, it can be the same where Cyclops core is deployed as well as the Controller host or a separated VM. 

It communicates with the controller by the parameters set in the [configuration file](https://github.com/icclab/cyclops/blob/master/collectors/openstack-ceilometer/config/openstack-ceilometer.conf), you have a guide in [it's wiki](https://github.com/icclab/cyclops/wiki/OpenStack-Ceilometer).

You can install all the components in a separate VM as well as in the controller, As long as you set up properly the configuration files, there is no problem. 

Cyclops 2.0 is supported by the Cyclops Dashboard. If you want to see the usage/charge/bill by userIds, we would recommend you to use the master branch currently. Otherwise if you want to see the usage/charge/bill by tenantIds/projectIds you use the support_keystone_authentication branch. We are currently working on the userId support for keystone authentication but will take some time before it can be released.

Please, let us know if you could install everything properly.
Cheers, 
Cyclops team.

**Comment by omkartelee08** [comment]
hi,

I am able to find out whether I am missing any command here,


![image](https://cloud.githubusercontent.com/assets/14068930/22777264/ba1fffee-eed8-11e6-9b72-3992e93c9d63.png)

how to start installation of dashboard ?

**Comment by ManuPerezBelmonte** [comment]
Good catch, this is updated now.

**Comment by omkartelee08** [comment]
on which port desktop is accessible ? I am not able to see on 80 or 8080 port.

**Comment by ManuPerezBelmonte** [comment]
you should be able to access it by :8080/login

2017-02-09 11:15 GMT+01:00 omkartelee08 <notifications@github.com>:

**Comment by omkartelee08** [comment]
How authentication is handled ? Where do I need to mention username/password ? No presence of GateKeeper I am able to find out. Extremely sorry if I am asking some basic questions.

**Comment by ManuPerezBelmonte** [comment]
Don't worry about asking this questions, we are pleased to answer everything that is needed.

If you are downloading the Master branch of Cyclops Dashboard, It currently does not support any authentication mechanism. To access to any user's usage/charge/billing pages, you can simply use the UserId as a username for login and any password to access. We are working on adding Gatekeeper to it, but it is still not finished. This will be updated as soon as it's finished in Cyclops Dashboard's repository.

If you are downloading Cyclops Dashboard from the support_keystone_authentication branch, the authentication is handled directly by keystone using the parameters defined on Dashboard's configuration file. This however, is currently linked to the usecase where the usage is generated for tenantId, not userId. This is due to our internal interaction with keystone and can be used with the OpenStack Event Collector, however and due to some other requests, we are trying to make the Dashboard work with keystone and give userId usages.

Hope it helped you, please let us know if you could log in and see the user usages.

Cheers

**Comment by omkartelee08** [comment]
I am trying to install "openstack_events" here, where do I need to provide controller details ? which API version of keystone is supported ?

**Comment by ManuPerezBelmonte** [comment]
Hello, 

You can define all the needed controller details in the configuration file of every microservice, including the collector. You will find it under the conf folder.
Cyclops Dashboard is currently supporting keystone v2.0.

If you have Cyclops core installed, the dashboard and the OpenStack event collector with every configuration file pointing to the correct endpoints, everything should work out of the box. 

Please let us know if you could solve the problem.

Cheers

**Comment by suri1694** [comment]
Hi,
I am getting these errors. I am not able to make a cyclops.udr file. I don't know where I need to make this file. Can you suggest something?
![error](https://user-images.githubusercontent.com/29750597/28019962-54d84828-65a0-11e7-9c94-98e7c4dfe111.png)
![timeseries](https://user-images.githubusercontent.com/29750597/28019963-54de2fae-65a0-11e7-92d0-74f2bfd846d7.png)

**Comment by suri1694** [comment]
@ManuPerezBelmonte can you suggest something?

**Comment by ManuPerezBelmonte** [comment]
Hello @suri1694 ,

For what I can see, the UDR service seems to be trying to get a parameter value which is not defined. I would check our [wiki](https://github.com/icclab/cyclops/wiki) and see [our guide for the configuration files](https://github.com/icclab/cyclops/wiki/Configuration). As for the [packaging](https://github.com/icclab/cyclops/wiki/Deployment), we usually package the file via maven manually, not via IDE, this might be a problem if you IDE is not properly configured. 

Let us know if this helps you.

Cheers!

**Comment by srihas619** [comment]
@ManuPerezBelmonte  where are the files `install_dependencies.sh`,  `start_cyclops.sh`, `install_rabbitmq.sh`, etc ? Please help me if I am missing something.
P.S: I have cloned the current master branch

**Comment by ManuPerezBelmonte** [comment]
Hi @srihas619 ,

During last week we have been moving towards the Cyclops 3.0 release, the files that you're talking about are no longer used. 

Please try to work with the version 3.0, please let us know if you could install it so we will close the issue.

Cheers

**Comment by srihas619** [comment]
@ManuPerezBelmonte well, can you help me with the instructions for installation please?

**Comment by ManuPerezBelmonte** [comment]
Hi @srihas619 ,

Pull the latest code from the master branch and you can find all the information in our [wiki pages](https://github.com/icclab/cyclops/wiki).

There you have all the steps you need to follow.

Cheers
