### ISSUE TITLE
Openstack Ceilometer Collector vs Openstack Event Collector

### ISSUE THREAD

**Issue by Extrodox** [icclab/cyclops#7]
What is the difference between both of these? When to use which one?

**Comment by ManuPerezBelmonte** [comment]
Hello Extrodox, 

The difference regards in which data and how is it being pulled from OpenStack. 

- Ceilometer Collector asks pulls data from the Ceilometer service so, in order to use it, Ceilometer must be up and running. The collector will send a request every X seconds (defined in the configuration file) and for all the meters that the Ceilometer service provides (or specific ones defined in configuration file). 

- Event collector pulls data from OpenStack's inner messaging queue in order to get information from Nova, Neutron and Cinder. For example, every time a VM is created a message will arrive to the collector and Usage Data will be generated. 

Depending in which kind of data would you like to have you can use one, the other or both. Ceilometer Collector will give you the data that [Ceilometer meters itself provide](http://docs.openstack.org/developer/ceilometer/webapi/v2.html#meters). However, the Event Collector will give you Up-Time data for meters such as CPU Uptime, Memory Uptime, Assigned floating IP uptime, Disk uptime...

Let us know if this helped you.
Cheers,

Cyclops team.

**Comment by Extrodox** [comment]
Thank you, this literally helped
